package InterfazPrincipal.ENUMS;

/*Esta lista de manera más que obvia no fue hecha por mí,
* está hecha con IA*/

public enum Paises{
    AFGHANISTAN("Afganistán", "+93"),
    ALBANIA("Albania", "+355"),
    ALGERIA("Argelia", "+213"),
    ANDORRA("Andorra", "+376"),
    ANGOLA("Angola", "+244"),
    ANTIGUA_AND_BARBUDA("Antigua y Barbuda", "+1-268"),
    ARGENTINA("Argentina", "+54"),
    ARMENIA("Armenia", "+374"),
    AUSTRALIA("Australia", "+61"),
    AUSTRIA("Austria", "+43"),
    AZERBAIJAN("Azerbaiyán", "+994"),
    BAHAMAS("Bahamas", "+1-242"),
    BAHRAIN("Bahréin", "+973"),
    BANGLADESH("Bangladés", "+880"),
    BARBADOS("Barbados", "+1-246"),
    BELARUS("Bielorrusia", "+375"),
    BELGIUM("Bélgica", "+32"),
    BELIZE("Belice", "+501"),
    BENIN("Benín", "+229"),
    BHUTAN("Bután", "+975"),
    BOLIVIA("Bolivia", "+591"),
    BOSNIA_AND_HERZEGOVINA("Bosnia y Herzegovina", "+387"),
    BOTSWANA("Botsuana", "+267"),
    BRAZIL("Brasil", "+55"),
    BRUNEI("Brunéi", "+673"),
    BULGARIA("Bulgaria", "+359"),
    BURKINA_FASO("Burkina Faso", "+226"),
    BURUNDI("Burundi", "+257"),
    CABO_VERDE("Cabo Verde", "+238"),
    CAMBODIA("Camboya", "+855"),
    CAMEROON("Camerún", "+237"),
    CANADA("Canadá", "+1"),
    CENTRAL_AFRICAN_REPUBLIC("República Centroafricana", "+236"),
    CHAD("Chad", "+235"),
    CHILE("Chile", "+56"),
    CHINA("China", "+86"),
    COLOMBIA("Colombia", "+57"),
    COMOROS("Comoras", "+269"),
    CONGO_DEMOCRATIC_REPUBLIC("República Democrática del Congo", "+243"),
    CONGO_REPUBLIC("República del Congo", "+242"),
    COSTA_RICA("Costa Rica", "+506"),
    COTE_D_IVOIRE("Costa de Marfil", "+225"),
    CROATIA("Croacia", "+385"),
    CUBA("Cuba", "+53"),
    CYPRUS("Chipre", "+357"),
    CZECH_REPUBLIC("República Checa", "+420"),
    DENMARK("Dimanarca", "+45"),
    DJIBOUTI("Yibuti", "+253"),
    DOMINICA("Dominica", "+1-767"),
    DOMINICAN_REPUBLIC("República Dominicana", "+1-809"),
    ECUADOR("Ecuador", "+593"),
    EGYPT("Egipto", "+20"),
    EL_SALVADOR("El Salvador", "+503"),
    EQUATORIAL_GUINEA("Guinea Ecuatorial", "+240"),
    ERITREA("Eritrea", "+291"),
    ESTONIA("Estonia", "+372"),
    ESWATINI("Eswatini", "+268"),
    ETHIOPIA("Etiopía", "+251"),
    FIJI("Fiyi", "+679"),
    FINLAND("Finlandia", "+358"),
    FRANCE("Francia", "+33"),
    GABON("Gabón", "+241"),
    GAMBIA("Gambia", "+220"),
    GEORGIA("Georgia", "+995"),
    GERMANY("Alemania", "+49"),
    GHANA("Ghana", "+233"),
    GREECE("Grecia", "+30"),
    GRENADA("Granada", "+1-473"),
    GUATEMALA("Guatemala", "+502"),
    GUINEA("Guinea", "+224"),
    GUINEA_BISSAU("Guinea-Bisáu", "+245"),
    GUYANA("Guyana", "+592"),
    HAITI("Haití", "+509"),
    HONDURAS("Honduras", "+504"),
    HUNGARY("Hungría", "+36"),
    ICELAND("Islandia", "+354"),
    INDIA("India", "+91"),
    INDONESIA("Indonesia", "+62"),
    IRAN("Irán", "+98"),
    IRAQ("Irak", "+964"),
    IRELAND("Irlanda", "+353"),
    ISRAEL("Israel", "+972"),
    ITALY("Italia", "+39"),
    JAMAICA("Jamaica", "+1-876"),
    JAPAN("Japón", "+81"),
    JORDAN("Jordania", "+962"),
    KAZAKHSTAN("Kazajistán", "+7"),
    KENYA("Kenia", "+254"),
    KIRIBATI("Kiribati", "+686"),
    NORTH_KOREA("Corea del Norte", "+850"),
    SOUTH_KOREA("Corea del Sur", "+82"),
    KUWAIT("Kuwait", "+965"),
    KYRGYZSTAN("Kirguistán", "+996"),
    LAOS("Laos", "+856"),
    LATVIA("Letonia", "+371"),
    LEBANON("Líbano", "+961"),
    LESOTHO("Lesoto", "+266"),
    LIBERIA("Liberia", "+231"),
    LIBYA("Libia", "+218"),
    LIECHTENSTEIN("Liechtenstein", "+423"),
    LITHUANIA("Lituania", "+370"),
    LUXEMBOURG("Luxemburgo", "+352"),
    MADAGASCAR("Madagascar", "+261"),
    MALAWI("Malaui", "+265"),
    MALAYSIA("Malasia", "+60"),
    MALDIVES("Maldivas", "+960"),
    MALI("Malí", "+223"),
    MALTA("Malta", "+356"),
    MARSHALL_ISLANDS("Islas Marshall", "+692"),
    MAURITANIA("Mauritania", "+222"),
    MAURITIUS("Mauricio", "+230"),
    MEXICO("México", "+52"),
    MICRONESIA("Micronesia", "+691"),
    MOLDOVA("Moldavia", "+373"),
    MONACO("Mónaco", "+377"),
    MONGOLIA("Mongolia", "+976"),
    MONTENEGRO("Montenegro", "+382"),
    MOROCCO("Marruecos", "+212"),
    MOZAMBIQUE("Mozambique", "+258"),
    MYANMAR("Birmania", "+95"),
    NAMIBIA("Namibia", "+264"),
    NAURU("Nauru", "+674"),
    NEPAL("Nepal", "+977"),
    NETHERLANDS("Países Bajos", "+31"),
    NEW_ZEALAND("Nueva Zelanda", "+64"),
    NICARAGUA("Nicaragua", "+505"),
    NIGER("Níger", "+227"),
    NIGERIA("Nigeria", "+234"),
    NORTH_MACEDONIA("Macedonia del Norte", "+389"),
    NORWAY("Noruega", "+47"),
    OMAN("Omán", "+968"),
    PAKISTAN("Pakistán", "+92"),
    PALAU("Palaos", "+680"),
    PALESTINE("Palestina", "+970"),
    PANAMA("Panamá", "+507"),
    PAPUA_NEW_GUINEA("Papúa Nueva Guinea", "+675"),
    PARAGUAY("Paraguay", "+595"),
    PERU("Perú", "+51"),
    PHILIPPINES("Filipinas", "+63"),
    POLAND("Polonia", "+48"),
    PORTUGAL("Portugal", "+351"),
    QATAR("Catar", "+974"),
    ROMANIA("Rumania", "+40"),
    RUSSIA("Rusia", "+7"),
    RWANDA("Ruanda", "+250"),
    SAINT_KITTS_AND_NEVIS("San Cristóbal y Nieves", "+1-869"),
    SAINT_LUCIA("Santa Lucía", "+1-758"),
    SAINT_VINCENT("San Vicente y las Granadinas", "+1-784"),
    SAMOA("Samoa", "+685"),
    SAN_MARINO("San Marino", "+378"),
    SAO_TOME_AND_PRINCIPE("Santo Tomé y Príncipe", "+239"),
    SAUDI_ARABIA("Arabia Saudita", "+966"),
    SENEGAL("Senegal", "+221"),
    SERBIA("Serbia", "+381"),
    SEYCHELLES("Seychelles", "+248"),
    SIERRA_LEONE("Sierra Leona", "+232"),
    SINGAPORE("Singapur", "+65"),
    SLOVAKIA("Eslovaquia", "+421"),
    SLOVENIA("Eslovenia", "+386"),
    SOLOMON_ISLANDS("Islas Salomón", "+677"),
    SOMALIA("Somalia", "+252"),
    SOUTH_AFRICA("Sudáfrica", "+27"),
    SOUTH_SUDAN("Sudán del Sur", "+211"),
    SPAIN("España", "+34"),
    SRI_LANKA("Sri Lanka", "+94"),
    SUDAN("Sudán", "+249"),
    SURINAME("Surinam", "+597"),
    SWEDEN("Suecia", "+46"),
    SWITZERLAND("Suiza", "+41"),
    SYRIA("Siria", "+963"),
    TAIWAN("Taiwán", "+886"),
    TAJIKISTAN("Tayikistán", "+992"),
    TANZANIA("Tanzania", "+255"),
    THAILAND("Tailandia", "+66"),
    TIMOR_LESTE("Timor Oriental", "+670"),
    TOGO("Togo", "+228"),
    TONGA("Tonga", "+676"),
    TRINIDAD_AND_TOBAGO("Trinidad y Tobago", "+1-868"),
    TUNISIA("Túnez", "+216"),
    TURKEY("Turquía", "+90"),
    TURKMENISTAN("Turkmenistán", "+993"),
    TUVALU("Tuvalu", "+688"),
    UGANDA("Uganda", "+256"),
    UKRAINE("Ucrania", "+380"),
    UNITED_ARAB_EMIRATES("Emiratos Árabes Unidos", "+971"),
    UNITED_KINGDOM("Reino Unido", "+44"),
    UNITED_STATES("Estados Unidos", "+1"),
    URUGUAY("Uruguay", "+598"),
    UZBEKISTAN("Uzbekistán", "+998"),
    VANUATU("Vanuatu", "+678"),
    VATICAN_CITY("Ciudad del Vaticano", "+39"),
    VENEZUELA("Venezuela", "+58"),
    VIETNAM("Vietnam", "+84"),
    YEMEN("Yemen", "+967"),
    ZAMBIA("Zambia", "+260"),
    ZIMBABWE("Zimbabue", "+263");

    private final String nombre;
    private final String extensionTelefonica;

    Paises(String nombre, String extensionTelefonica) {
        this.nombre = nombre;
        this.extensionTelefonica = extensionTelefonica;
    }

    public String getNombre() {
        return nombre;
    }

    public String getExtensionTelefonica() {
        return extensionTelefonica;
    }
}


